### ISSUE TITLE
Add NLP functionality to txt routes

### ISSUE THREAD

**Issue by Fdawgs** [Fdawgs/docsmith#567]
### Prerequisites

- [X] I have written a descriptive title
- [X] I have searched existing feature requests to ensure it has not already been proposed

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### Description

Natural Language Processing (NLP) functionality would be beneficial to both [Yeovil District Hospital NHS Foundation Trust](https://yeovilhospital.co.uk/) and [Somerset NHS Foundation Trust](https://www.somersetft.nhs.uk/) as [parsing of unstructured data into structured data is needed](https://github.com/Fdawgs/ydh-toc-itk3#issues-with-migration-from-current-processes) for adoption of NHS Digital's [ITK3](https://digital.nhs.uk/services/interoperability-toolkit/developer-resources/itk3-test-harness/itk3-messaging-distribution-specification-versions) [Transfer of Care](https://digital.nhs.uk/services/interoperability-toolkit/developer-resources/transfer-of-care-specification-versions) FHIR resource bundles.

# Tasks
- [ ] Identify small uses for NLP
  - Finding patient identifiers, like their NHS number
  - Finding department names
  - Finding appointment dates
  - Finding consultant/healthcare professional sign off
- [ ] Investigate NLP packages
   - [ ] [Compromise](https://github.com/spencermountain/compromise)
   - [ ] [Retext](https://github.com/retextjs/retext)
   - [ ] [Natural](https://github.com/NaturalNode/natural)
- [ ] Integrate NLP package into Fastify plugin
- [ ] Require plugin for txt routes
- [ ] Add boolean query string param to routes and schemas

**Comment by Fdawgs** [comment]
Incredibly heavy and deserves to be its own API.
